# Generated by Django 6.0.6 on 2026-09-04 16:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_skills', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('punctuality', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('problem_solving', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('professionalism', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('work_quality', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('learning_ability', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('discipline', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('strengths', models.TextField(blank=True)),
                ('improvement_areas', models.TextField(blank=True)),
                ('overall_comments', models.TextField(blank=True)),
                ('final_recommendation', models.CharField(choices=[('HIGHLY_RECOMMENDED', 'Highly Recommended'), ('RECOMMENDED', 'Recommended'), ('RECOMMENDED_WITH_IMPROVEMENT', 'Recommended with Improvement'), ('NOT_RECOMMENDED', 'Not Recommended')], max_length=50)),
                ('overall_score', models.FloatField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='interns.internship')),
            ],
            options={
                'verbose_name': 'evaluation',
                'verbose_name_plural': 'evaluations',
                'ordering': ['-created_at'],
            },
        ),
    ]
