# Generated by Django 6.0.6 on 2026-09-07 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Document Title')),
                ('category', models.CharField(choices=[('IDENTITY', 'Identity / Citizenship'), ('ACADEMIC', 'Academic Document'), ('INTERNSHIP_LETTER', 'Internship Letter'), ('PROJECT_REPORT', 'Project Report'), ('COMPLETION_CERT', 'Completion Certificate'), ('OTHER', 'Other')], default='OTHER', max_length=50, verbose_name='Category')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='File')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description / Notes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='interns.internprofile', verbose_name='Intern')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
