# Generated by Django 6.0.6 on 2026-08-31 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='log date')),
                ('title', models.CharField(max_length=255, verbose_name='activity title')),
                ('description', models.TextField(verbose_name='description / activities performed')),
                ('skills_learned', models.TextField(blank=True, verbose_name='skills learned')),
                ('challenges', models.TextField(blank=True, verbose_name='problems / challenges')),
                ('hours_worked', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='hours worked')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='status')),
                ('supervisor_feedback', models.TextField(blank=True, verbose_name='supervisor feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='interns.internprofile', verbose_name='intern')),
            ],
            options={
                'verbose_name': 'daily log',
                'verbose_name_plural': 'daily logs',
                'ordering': ['-date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('intern', 'date'), name='unique_intern_date_dailylog')],
            },
        ),
    ]
