# Generated by Django 6.0.6 on 2026-08-30 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='department name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InternProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intern_id', models.CharField(max_length=50, unique=True, verbose_name='intern ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone number')),
                ('college', models.CharField(blank=True, max_length=200, verbose_name='college / university')),
                ('program', models.CharField(blank=True, max_length=100, verbose_name='program / degree')),
                ('semester_or_year', models.CharField(blank=True, max_length=50, verbose_name='semester / year')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/interns/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'INTERN'}, on_delete=django.db.models.deletion.CASCADE, related_name='intern_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'intern profile',
                'verbose_name_plural': 'intern profiles',
                'ordering': ['intern_id'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='employee ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone number')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='position / designation')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/supervisors/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisors', to='interns.department')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'SUPERVISOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'supervisor profile',
                'verbose_name_plural': 'supervisor profiles',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='position / role')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('expected_end_date', models.DateField(verbose_name='expected end date')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='actual end date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internships', to='interns.department')),
                ('intern', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internship', to='interns.internprofile')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_internships', to='interns.supervisorprofile')),
            ],
            options={
                'verbose_name': 'internship',
                'verbose_name_plural': 'internships',
                'ordering': ['-start_date'],
            },
        ),
    ]
