# Generated by Django 6.0.6 on 2026-08-30 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='attendance date')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='check-in time')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='check-out time')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LEAVE', 'Leave'), ('ABSENT', 'Absent')], default='PRESENT', max_length=20, verbose_name='status')),
                ('remarks', models.TextField(blank=True, verbose_name='remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='interns.internprofile')),
            ],
            options={
                'verbose_name': 'attendance record',
                'verbose_name_plural': 'attendance records',
                'ordering': ['-date', '-check_in'],
                'constraints': [models.UniqueConstraint(fields=('intern', 'date'), name='unique_intern_date_attendance')],
            },
        ),
    ]
